### ISSUE TITLE
How to change group data colspan to rowspan?

### ISSUE THREAD

**Issue by kranthibhagath** [karenpommeroy/dc-tableview#1]
Hai i am working on dc project i got a issue on data table
i want to mearge row data in group 
can any one suggest me how to do it
i want to mearge those empty cells
![untitled](https://user-images.githubusercontent.com/31399202/32132682-b96b6400-bbe5-11e7-8847-e00e9a3604ca.png)

**Comment by karenpommeroy** [comment]
First suggestion that comes to my mind is just removing table cell borders with css.

However when I look at datatables plugin (used by dc-tableview) website it seems that grouped rows are presented somehow differently (should be [https://datatables.net/extensions/rowgroup/examples/initialisation/startAndEndRender.html](https://datatables.net/extensions/rowgroup/examples/initialisation/startAndEndRender.html))

Maybe that's just some setting for RowGroup extension ([https://datatables.net/extensions/rowgroup/examples/](https://datatables.net/extensions/rowgroup/examples/)) or a matter of datatables version but I'll need to investigate that.

**Comment by kranthibhagath** [comment]
i want to show the table in row grouping formatt

**Comment by karenpommeroy** [comment]
Ah your image suggested that there is something wrong with grouping so that it leaves empty cells :)

So in order to achieve what you want I would just go with css.
Here is an example how to remove column borders from inner cells: [http://jsfiddle.net/azq6xfnr/49/](http://jsfiddle.net/azq6xfnr/49/)
