### ISSUE TITLE
how to bind tableview to other dc charts

### ISSUE THREAD

**Issue by toddlamothe** [karenpommeroy/dc-tableview#2]
I have a page containing a set of dc.js pie and row charts bound together with crossfilter. Can I add a tableview that is bound to the same crossfilter object and filtered dynamically as the other charts are filtered?

**Comment by karenpommeroy** [comment]
Hi,
That's the way it's supposed to work to begin with.
Once you add dc.tableview it uses data() function to obtain data when rendering and this returns the data that represents current state (with filters).

**Comment by toddlamothe** [comment]
Are there any examples showing how tableview works with other charts on the page? Only examples I can find are stand-alone tableview.

**Comment by karenpommeroy** [comment]
I updated examples with this [https://github.com/karenpommeroy/dc-tableview/commit/c2665a80af1b1bd71d4ea240e4cca9c164a89f5c](commit)

You might also wann update to 1.0.3 cause I fixed issue with synchronising with other charts.

**Comment by toddlamothe** [comment]
That worked, thank you for the updated example. My controls were not in the same group.
