### ISSUE TITLE
Usage guide with react

### ISSUE THREAD

**Issue by kiranrwone** [karenpommeroy/dc-tableview#7]
How to use dc-tableview in React.JS?
I have tried to import dc namespace so that `dc-tableview` can access it and define `dc.tableview`, but dc is not accessible inside `dc-tableview`.

```
import * as dc from 'dc';
import 'dc-tableview';
```

**Comment by privateOmega** [comment]
@karenpommeroy Hi Could you please take a look into this issue?

**Comment by karenpommeroy** [comment]
Hi,

Haven't actually tested it with react nor typescript.
Have you tried including it using simple require? i.e.
*require('dc-tableview.js')
Regards, Martin*

wt., 16 kwi 2019 o 08:46 Kiran Mathew Mohan <notifications@github.com>
napisał(a):

**Comment by privateOmega** [comment]
@karenpommeroy That's the thing, there's no require() in React, its all import, require() is only for node.js. I am thinking require() and import has some effect on loading things to global scope. I am not sure about it.

**Comment by karenpommeroy** [comment]
Ahh sorry I don't know why I assumed it's server side (maybe cause I'm
doing backend project myself currently).

I think you can use require if you disable tslint warnings.
Other solution I can think of now is to include as script in your html file.

Regards

wt., 16 kwi 2019 o 18:27 Kiran Mathew Mohan <notifications@github.com>
napisał(a):

**Comment by privateOmega** [comment]
Haha no issues. Even I am a backend dev, testing my feet in frontend dev. I wasn't aware that you could disable it like that, I will check it out. Thanks. Oh yes that should do importing script directly,  that thought never crossed my mind.

**Comment by privateOmega** [comment]
@karenpommeroy I haven't found anyway to use require() in React.JS yet. And also importing script directly into main html file isn't working out and importing script to .js file shows `unable to reach Datatable.net` error or something.

Could you please help me out, you might have more idea on how to use this in React.JS to work.

**Comment by gordonwoodhull** [comment]
Sorry, I don't have any experience with React yet. 

I have seen similar issues raised against D3 since it has modules which change other modules. Apparently some bundlers won't let you modify modules once they are loaded.

I don't recall seeing the solution but I'm sure one is out there. 😺

**Comment by privateOmega** [comment]
@gordonwoodhull Oh alright.

**Comment by gordonwoodhull** [comment]
I don't want to add the extra dependency, since dc.js doesn't currently depend on DataTables.js.

For your own use I'm sure you could just paste the class from this library into dc.js 2.*. That's probably easier than figuring out how the bundlers work.

**Comment by privateOmega** [comment]
Okay @gordonwoodhull

**Comment by dahlbyk** [comment]
You should be able to assign `global.dc = dc` to expose `dc` to `dc-tableview`.

**Comment by privateOmega** [comment]
@dahlbyk where would I do that? And it doesn't work for me. Is this for React?
And could you please point me to an example, so I could be sure this approach works.

What I have done
```
import React from 'react';
import * as dc from 'dc';
import * as d3 from 'd3';
import 'dc-tableview';

global.dc = dc;
```

**Comment by satra2806** [comment]
@privateOmega  , you got the solution ?, i am also working on this.

**Comment by privateOmega** [comment]
@satra2806 Sorry, I don't remember what I had done or why I had closed this issue.
