### ISSUE TITLE
JQuery dependency throws audit error in npm

### ISSUE THREAD

**Issue by elChapoSing** [karenpommeroy/dc-tableview#8]
![image](https://user-images.githubusercontent.com/5416611/67062629-744b6f80-f196-11e9-93fb-c82dfb020461.png)

I'm assuming this is not an actual risk but should you update packages in NPM ?

**Comment by karenpommeroy** [comment]
Hi, you can make a commit with updated deps and I'll merge it or wait when
I release new version.

Thanks!

**Comment by elChapoSing** [comment]
#9

**Comment by karenpommeroy** [comment]
Fixed in 1.0.4
